apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dseregion2
spec:
  serviceName: "dse"
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      securityContext:
        fsGroup: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dse
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-opsc-up
        image: tutum/curl
        command: ['sh', '-c', 'until curl -k https://${OPSC_DNS}:8443; do echo waiting for OPSC; sleep 5; done;']
        env:
        - name: OPSC_DNS
          value: opscenter-0.cassandra.dse
      containers:
      - name: dnsregister
        image: riccardopomato/dnsregister
        env:
        - name: DnsProvider
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: DnsProvider
        - name: IBM_DnsZone_ID
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: IBM_DnsZone_ID
        - name: IBM_DnsZone_Instance_ID
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: IBM_DnsZone_Instance_ID
        - name: IBM_APIKEY
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: IBM_APIKEY           
      - name: dse
        image: datastax/dse-server:6.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: "2000Mi"
        env:
        - name: DS_LICENSE
          value: accept
        - name: SEEDS
          value: dseregion1-0.cassandra.dse,dseregion1-1.cassandra.dse
        - name: CLUSTER_NAME
          value: "My_Cluster"
        - name: NUM_TOKENS
          value: "64"
        - name: DC
          value: "DC-1"
        - name: RACK
          value: "rack-1"
        - name: OPSCENTER_IP
          value: opscenter-0.cassandra.dse
        - name: SNITCH
          value: GossipingPropertyFileSnitch
        args:
        - '-s'
        ports:
        - containerPort: 7000
          name: intra-node-port
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx-port
        - containerPort: 8609
          name: inter-node-msg
        - containerPort: 9042
          name: cql-port
        - containerPort: 9160
          name: thrift-port
        - containerPort: 8983
          name: solr-port
        - containerPort: 8984
          name: solr-int-node
        - containerPort: 4040
          name: spark-app-port
        - containerPort: 7077
          name: spark-int-node
        - containerPort: 7080
          name: spark-m-web
        - containerPort: 7081
          name: spark-w-web
        - containerPort: 8090
          name: spark-job
        - containerPort: 9999
          name: spark-job-jmx
        - containerPort: 18080
          name: spark-histor
        - containerPort: 8182
          name: gremlin-port
        - containerPort: 5598
          name: dsefs-public
        - containerPort: 5599
          name: dsefs-private
        - containerPort: 61621
          name: ds-agent-port
        volumeMounts:
        - name: dse-data
          mountPath: /var/lib/cassandra
        - name: config-volume
          mountPath: /config
        livenessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 900
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "exec nodetool decommission"]
      volumes:
      - name: config-volume
        configMap:
          name: dse-config
  volumeClaimTemplates:
  - metadata:
      name: dse-data
    spec:
      storageClassName: "ibmc-block-retain-silver"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dse-cluster-init-job
  labels:
    app: dse
spec:
  template:
    spec:
      initContainers:
      - name: init-opsc-up
        image: tutum/curl
        command: ['sh', '-c', 'until curl -k https://${OPSC_DNS}:8443; do echo waiting for OPSC; sleep 5; done;']
        env:
        - name: OPSC_DNS
          value: opscenter-0.cassandra.dse
      containers:
      - name: dse-cluster-init
        image: gcr.io/datastax-public/dse-cluster-init:6.5.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SEED_DNS
          value: dseregion1-0.cassandra.dse,dseregion1-1.cassandra.dse
        - name: CLUSTER_NAME
          value: "My_Cluster"
        - name: CLUSTER_SIZE
          value: "3"
        - name: OPSC_DNS
          value: opscenter-0.cassandra.dse
        - name: OPSC_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opsc
              key: admin_password
      restartPolicy: Never
  backoffLimit: 8
